### ISSUE TITLE
python---IOError: No Default Input Device Available

### ISSUE THREAD

**Issue by vishallight** [shichao-an/soundmeter#25]
~# python -m speech_recognition 
ALSA lib pcm_dsnoop.c:638:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1099:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_dsnoop.c:638:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1099:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1099:(snd_pcm_dmix_open) unable to open slave
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/speech_recognition/__main__.py", line 4, in <module>
    m = sr.Microphone()
  File "/usr/local/lib/python2.7/dist-packages/speech_recognition/__init__.py", line 86, in __init__
    device_info = audio.get_device_info_by_index(device_index) if device_index is not None else audio.get_default_input_device_info()
  File "/usr/local/lib/python2.7/dist-packages/pyaudio.py", line 949, in get_default_input_device_info
    device_index = pa.get_default_input_device()
IOError: No Default Input Device Available
_________________________________________________________________________________
what to do ?anyone can fix this

**Comment by shichao-an** [comment]
You can try to find your input device index, and set `input_device_index` in the config. See #7 for more details

**Comment by hborah1** [comment]
> You can try to find your input device index, and set `input_device_index` in the config. See #7 for more details

the input_device_index wont work because there are no input devices

**Comment by user-sam** [comment]
hi programmers I have also the same issue in my google colab,
-This is the full error-??
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-9-bc266b7be21f> in <module>()
----> 1 from speech_recognition import __main__

2 frames
/usr/local/lib/python3.6/dist-packages/pyaudio.py in get_default_input_device_info(self)
    947         """
    948 
--> 949         device_index = pa.get_default_input_device()
    950         return self.get_device_info_by_index(device_index)
    951 

OSError: No Default Input Device Available

----------------------------

how can I solve this error in colab

((----- :(
I think I need to set input device and give permission to access it !

Can any one please help me!!

**Comment by savitha91** [comment]
Hi I am facing the same issue. Did it work ? If so please post a solution

**Comment by user-sam** [comment]
Hi @savitha91, please tell me are you running your program in or you system or if you are running your program in online environment such as Google Collab or in kaggle kernal etc.

**Comment by bharathreddy3468** [comment]
> Hi @savitha91, please tell me are you running your program in or you system or if you are running your program in online environment such as Google Collab or in kaggle kernal etc.

hi, i'm using google collab and how can i access my microphone using speech recognition from collab

**Comment by bharathreddy3468** [comment]
> ## hi programmers I have also the same issue in my google colab,
> -This is the full error-??
> OSError Traceback (most recent call last)
> in ()
> ----> 1 from speech_recognition import **main**
> 
> 2 frames
> /usr/local/lib/python3.6/dist-packages/pyaudio.py in get_default_input_device_info(self)
> 947 """
> 948
> --> 949 device_index = pa.get_default_input_device()
> 950 return self.get_device_info_by_index(device_index)
> 951
> 
> OSError: No Default Input Device Available
> 
> how can I solve this error in colab
> 
> ((----- :(
> I think I need to set input device and give permission to access it !
> 
> Can any one please help me!!

even i have the same problem can anybody fix this

**Comment by ShhrutiDeka** [comment]
I found this piece of code exclusive to use local microphone via colab.
Although I can't seem to extract the audio file without saving for my speech to text requirement.

`#in colab

!pip install ffmpeg-python
import ffmpeg
from IPython.display import HTML, Audio
from google.colab.output import eval_js
from base64 import b64decode
import numpy as np
from scipy.io.wavfile import read as wav_read
import io

AUDIO_HTML = """
<script>
var my_div = document.createElement("DIV");
var my_p = document.createElement("P");
var my_btn = document.createElement("BUTTON");
var t = document.createTextNode("Press to start recording");

my_btn.appendChild(t);
//my_p.appendChild(my_btn);
my_div.appendChild(my_btn);
document.body.appendChild(my_div);

var base64data = 0;
var reader;
var recorder, gumStream;
var recordButton = my_btn;

var handleSuccess = function(stream) {
  gumStream = stream;
  var options = {
    //bitsPerSecond: 8000, //chrome seems to ignore, always 48k
    mimeType : 'audio/webm;codecs=opus'
    //mimeType : 'audio/webm;codecs=pcm'
  };            
  //recorder = new MediaRecorder(stream, options);
  recorder = new MediaRecorder(stream);
  recorder.ondataavailable = function(e) {            
    var url = URL.createObjectURL(e.data);
    var preview = document.createElement('audio');
    preview.controls = true;
    preview.src = url;
    document.body.appendChild(preview);

    reader = new FileReader();
    reader.readAsDataURL(e.data); 
    reader.onloadend = function() {
      base64data = reader.result;
      //console.log("Inside FileReader:" + base64data);
    }
  };
  recorder.start();
  };

recordButton.innerText = "Recording... press to stop";

navigator.mediaDevices.getUserMedia({audio: true}).then(handleSuccess);


function toggleRecording() {
  if (recorder && recorder.state == "recording") {
      recorder.stop();
      gumStream.getAudioTracks()[0].stop();
      recordButton.innerText = "Saving the recording... pls wait!"
  }
}

// https://stackoverflow.com/a/951057
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

var data = new Promise(resolve=>{
//recordButton.addEventListener("click", toggleRecording);
recordButton.onclick = ()=>{
toggleRecording()

sleep(2000).then(() => {
  // wait 2000ms for the data to be available...
  // ideally this should use something like await...
  //console.log("Inside data:" + base64data)
  resolve(base64data.toString())

});

}
});
      
</script>
"""

def get_audio():
  display(HTML(AUDIO_HTML))
  data = eval_js("data")
  binary = b64decode(data.split(',')[1])
  
  process = (ffmpeg
    .input('pipe:0')
    .output('pipe:1', format='wav')
    .run_async(pipe_stdin=True, pipe_stdout=True, pipe_stderr=True, quiet=True, overwrite_output=True)
  )
  output, err = process.communicate(input=binary)
  
  riff_chunk_size = len(output) - 8
  # Break up the chunk size into four bytes, held in b.
  q = riff_chunk_size
  b = []
  for i in range(4):
      q, r = divmod(q, 256)
      b.append(r)

  # Replace bytes 4:8 in proc.stdout with the actual size of the RIFF chunk.
  riff = output[:4] + bytes(b) + output[8:]

  sr, audio = wav_read(io.BytesIO(riff))

  return audio, sr, riff

audio, sr, riff = get_audio()`
