### ISSUE TITLE
maxChans failed

### ISSUE THREAD

**Issue by Blyzz616** [shichao-an/soundmeter#29]
Hi there,

I'm trying to get your soundmeter working on a Raspberry Pi Zero W.

I'm getting the following error when I try do anything:

Expression 'parameters->channelCount <= maxChans' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1514
Expression 'ValidateParameters( inputParameters, hostApi, StreamDirection_In )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2818
Traceback (most recent call last):
  File "/usr/local/bin/soundmeter", line 11, in <module>
    load_entry_point('soundmeter==0.1.5', 'console_scripts', 'soundmeter')()
  File "/usr/local/lib/python2.7/dist-packages/soundmeter/meter.py", line 321, in main
    m = Meter(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/soundmeter/meter.py", line 66, in __init__
    frames_per_buffer=self.config.FRAMES_PER_BUFFER)
  File "/usr/local/lib/python2.7/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
IOError: [Errno -9998] Invalid number of channels

I have no experience with Python, so not sure what I'm looking at here.

**Comment by krzyk** [comment]
Same issue on my side, Raspberry Pi 3B+ with an usb mic

**Comment by krzyk** [comment]
@Blyzz616 This is solved in https://github.com/shichao-an/soundmeter/issues/1 (you need to create a config with a `channel = 1`
